version: '3.1'
services:
  db:
     image: mysql:8.0.23
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: labforward
     ports:
       - "3306:3306"
